name = "Olympus Server"
author = "StarStorm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e802495d6ef8fe092a19fd3380352c198dd1857c26bf54f2c6007eaed815dc1b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
