name = "Olympus Server"
author = "StarStorm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f97d19b8bb7ef7829be7ccbb04a8ca14701679c543c0bec4bf6df9573fe739b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
